package kladionica.entity;
// Generated May 4, 2018 6:56:20 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "kladionica")
public class Category implements java.io.Serializable {

	private Integer idCategory;
	private String name;
	private Set<League> leagues = new HashSet<League>(0);

	public Category() {
	}

	public Category(String name, Set<League> leagues) {
		this.name = name;
		this.leagues = leagues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategory", unique = true, nullable = false)
	public Integer getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(Integer idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<League> getLeagues() {
		return this.leagues;
	}

	public void setLeagues(Set<League> leagues) {
		this.leagues = leagues;
	}

}
