package kladionica.entity;
// Generated May 4, 2018 6:56:20 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Komentar generated by hbm2java
 */
@Entity
@Table(name = "komentar", catalog = "kladionica")
public class Komentar implements java.io.Serializable {

	private int idKomentar;
	private Tema tema;
	private User user;
	private String sadrzaj;
	private Date vremeidatum;

	public Komentar() {
	}

	public Komentar(int idKomentar, Tema tema, User user) {
		this.idKomentar = idKomentar;
		this.tema = tema;
		this.user = user;
	}

	public Komentar(int idKomentar, Tema tema, User user, String sadrzaj, Date vremeidatum) {
		this.idKomentar = idKomentar;
		this.tema = tema;
		this.user = user;
		this.sadrzaj = sadrzaj;
		this.vremeidatum = vremeidatum;
	}

	@Id

	@Column(name = "idKomentar", unique = true, nullable = false)
	public int getIdKomentar() {
		return this.idKomentar;
	}

	public void setIdKomentar(int idKomentar) {
		this.idKomentar = idKomentar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tema_idTeme", nullable = false)
	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "sadrzaj", length = 45)
	public String getSadrzaj() {
		return this.sadrzaj;
	}

	public void setSadrzaj(String sadrzaj) {
		this.sadrzaj = sadrzaj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vremeidatum", length = 19)
	public Date getVremeidatum() {
		return this.vremeidatum;
	}

	public void setVremeidatum(Date vremeidatum) {
		this.vremeidatum = vremeidatum;
	}

}
