package kladionica.entity;
// Generated May 4, 2018 6:56:20 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * League generated by hbm2java
 */
@Entity
@Table(name = "league", catalog = "kladionica")
public class League implements java.io.Serializable {

	private Integer idLeague;
	private Category category;
	private String name;
	private Set<Match> matches = new HashSet<Match>(0);
	private Set<Team> teams = new HashSet<Team>(0);

	public League() {
	}

	public League(Category category) {
		this.category = category;
	}

	public League(Category category, String name, Set<Match> matches, Set<Team> teams) {
		this.category = category;
		this.name = name;
		this.matches = matches;
		this.teams = teams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLeague", unique = true, nullable = false)
	public Integer getIdLeague() {
		return this.idLeague;
	}

	public void setIdLeague(Integer idLeague) {
		this.idLeague = idLeague;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Category_idCategory", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "league")
	public Set<Match> getMatches() {
		return this.matches;
	}

	public void setMatches(Set<Match> matches) {
		this.matches = matches;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "team_has_league", catalog = "kladionica", joinColumns = {
			@JoinColumn(name = "League_idLeague", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Team_idTeam", nullable = false, updatable = false) })
	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

}
