package kladionica.entity;
// Generated May 4, 2018 6:56:20 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tema generated by hbm2java
 */
@Entity
@Table(name = "tema", catalog = "kladionica")
public class Tema implements java.io.Serializable {

	private int idTeme;
	private User user;
	private String naslovTeme;
	private String opisTeme;
	private Date vremeidatum;
	private Set<Komentar> komentars = new HashSet<Komentar>(0);

	public Tema() {
	}

	public Tema(int idTeme, User user) {
		this.idTeme = idTeme;
		this.user = user;
	}

	public Tema(int idTeme, User user, String naslovTeme, String opisTeme, Date vremeidatum, Set<Komentar> komentars) {
		this.idTeme = idTeme;
		this.user = user;
		this.naslovTeme = naslovTeme;
		this.opisTeme = opisTeme;
		this.vremeidatum = vremeidatum;
		this.komentars = komentars;
	}

	@Id

	@Column(name = "idTeme", unique = true, nullable = false)
	public int getIdTeme() {
		return this.idTeme;
	}

	public void setIdTeme(int idTeme) {
		this.idTeme = idTeme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "naslovTeme", length = 45)
	public String getNaslovTeme() {
		return this.naslovTeme;
	}

	public void setNaslovTeme(String naslovTeme) {
		this.naslovTeme = naslovTeme;
	}

	@Column(name = "opisTeme", length = 45)
	public String getOpisTeme() {
		return this.opisTeme;
	}

	public void setOpisTeme(String opisTeme) {
		this.opisTeme = opisTeme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vremeidatum", length = 19)
	public Date getVremeidatum() {
		return this.vremeidatum;
	}

	public void setVremeidatum(Date vremeidatum) {
		this.vremeidatum = vremeidatum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tema")
	public Set<Komentar> getKomentars() {
		return this.komentars;
	}

	public void setKomentars(Set<Komentar> komentars) {
		this.komentars = komentars;
	}

}
