package kladionica.entity;
// Generated May 4, 2018 6:56:20 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "kladionica")
public class User implements java.io.Serializable {

	private Integer idUser;
	private String name;
	private String lastname;
	private String email;
	private String username;
	private String password;
	private Double credit;
	private String role;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);
	private Set<Komentar> komentars = new HashSet<Komentar>(0);
	private Set<Tema> temas = new HashSet<Tema>(0);

	public User() {
	}

	public User(String name, String lastname, String email, String username, String password, Double credit,
			String role, Set<Ticket> tickets, Set<Komentar> komentars, Set<Tema> temas) {
		this.name = name;
		this.lastname = lastname;
		this.email = email;
		this.username = username;
		this.password = password;
		this.credit = credit;
		this.role = role;
		this.tickets = tickets;
		this.komentars = komentars;
		this.temas = temas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "credit", precision = 22, scale = 0)
	public Double getCredit() {
		return this.credit;
	}

	public void setCredit(Double credit) {
		this.credit = credit;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Komentar> getKomentars() {
		return this.komentars;
	}

	public void setKomentars(Set<Komentar> komentars) {
		this.komentars = komentars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Tema> getTemas() {
		return this.temas;
	}

	public void setTemas(Set<Tema> temas) {
		this.temas = temas;
	}

}
